source 'https://rubygems.org'

gem 'curburger',        :git => 'git://github.com/autumncollection/curburger.git'
gem 'glogg',            :git => 'git://github.com/autumncollection/glogg.git'
gem 'oj'
gem 'slim'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-content-for2'